### ISSUE TITLE
Umgang mit JQuery nicht mit anderen Plugins nicht immer kompatibel

### ISSUE THREAD

**Issue by McRange** [RonnyWeiss/Apex-Fancy-Tree-Select#14]
Hallo Ronny,
Mangels Zeit kann ich das Problem leider grade nicht nachbauen - sry dafür.

Auf einer APEX Seite wird ein normaler modaler Dialog geöffnet, auf welchem das Fancy-Tree-Plugin genutzt wird und per PageLoad-Dynamic Action das [APEX-Dynamic-Dialog-Title](https://github.com/RonnyWeiss/APEX-Dynamic-Dialog-Title) ausgeführt wird.

Dabei wird im Javascript zum Setzen des Dialog Titels aber ein Fehler verursacht:
`apex.util.getTopApex().jQuery(".ui-dialog-content").dialog("option","title", "Bla!");`

Error Stack:

> Uncaught Error: cannot call methods on dialog prior to initialization; attempted to call method 'option'
>     at Function.error (jquery-3.6.0.js?v=21.2.1:338:9)
>     at HTMLDivElement.<anonymous> (fancytree.pkgd.min.js:1:2074)
>     at Function.each (jquery-3.6.0.js?v=21.2.1:385:19)
>     at jQuery.fn.init.each (jquery-3.6.0.js?v=21.2.1:207:17)
>     at k.fn.<computed> [as dialog] (fancytree.pkgd.min.js:1:1818)
>     at HTMLDivElement.<anonymous> (f?p=30000:3270:6227315020229::YES:RP,3270:P3270_IDENT:4077&cs=3R-B_cItnZvNLv-RuqdPBurUwMyCLUHmxcz_IZSaMIjcahBz1dW1-UOt27bblO9QBYT2FRdc3myG8KbWgoGMRyg&p_dialog_cs=lWzITfnp94ovbpBq8EpLwlOUnJMGRB8Xrl_3FbvUgYwxpyzWk6PpnibzJgsctHRVN1zc271t_qkHiPtHx9MCwg:370:27)
>     at Function.each (jquery-3.6.0.js?v=21.2.1:385:19)
>     at jQuery.fn.init.each (jquery-3.6.0.js?v=21.2.1:207:17)
>     at Object.javascriptFunction (f?p=30000:3270:6227315020229::YES:RP,3270:P3270_IDENT:4077&cs=3R-B_cItnZvNLv-RuqdPBurUwMyCLUHmxcz_IZSaMIjcahBz1dW1-UOt27bblO9QBYT2FRdc3myG8KbWgoGMRyg&p_dialog_cs=lWzITfnp94ovbpBq8EpLwlOUnJMGRB8Xrl_3FbvUgYwxpyzWk6PpnibzJgsctHRVN1zc271t_qkHiPtHx9MCwg:367:260)
>     at da.doAction (dynamic_actions_core.js?v=21.2.1:597:47)

Beim Auflösen der **dialog**-Methode von **apex.util.getTopApex().jQuery** landet man plötzlich in der Datei **fancytree.pkgd.min.js**, was dann in Folge wohl zum eigentlichen Fehler führt. 
Die Verwendung von jedem der Plugins für sich alleine funktioniert hingegen. 
Mir scheint als würde der Fancy Tree das jQuery im APEX überschreiben.

**Comment by McRange** [comment]
Der Fix für [Issue #1](https://github.com/RonnyWeiss/APEX-Dynamic-Dialog-Title/issues/1) am Dynamic Dialog Title Plugin hat das Problem behoben. 
Dass das FancyTree Plugin jedoch irgendwie im jQuery vom Apex Methoden überschreibt, kommt mir trotzdem nicht korrekt vor. Wahrscheinlich lässt sich das generell mit jQuery.noConflict() vermeiden.
